[package]
name = "hill_descent"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = { version = "0.1.7", optional = true }

xxhash-rust = { version = "0.8", features = ["xxh3"] }
rand = { version = "0.8.5", features = ["small_rng", "std_rng"] }
getrandom = { version = "0.2", features = ["js"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = "0.2"
tracing = { version = "0.1", optional = true, features = ["attributes"] }
tracing-subscriber = { version = "0.3", optional = true, features = [
    "fmt",
    "std",
    "env-filter",
    "time",
] }
tracing-log = { version = "0.2", optional = true }
console_log = { version = "1.0", optional = true }
log = { version = "0.4", optional = true }
rand_chacha = "0.9.0"

[features]
wasm = ["console_error_panic_hook"]
enable-tracing = ["tracing", "tracing-subscriber", "tracing-log", "log", "console_log"]
wasm-logging = ["console_log", "log"]

[lib]
crate-type = ["cdylib", "rlib"]

[lints.rust]
unused = "warn"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "hundred_parameter_benchmark"
harness = false

[profile.bench]
debug = true
