[package]
name = "hill_descent_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = { version = "0.1.7", optional = true }
xxhash-rust = { workspace = true }
rand = { workspace = true }
getrandom = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
wasm-bindgen = "0.2"
tracing = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
tracing-log = { workspace = true, optional = true }
console_log = { version = "1.0", optional = true }
log = { version = "0.4", optional = true }
rand_chacha = { workspace = true }

[features]
wasm = ["console_error_panic_hook"]
enable-tracing = [
    "tracing",
    "tracing-subscriber",
    "tracing-log",
    "log",
    "console_log",
]
wasm-logging = ["console_log", "log"]

[lib]
crate-type = ["cdylib", "rlib"]

[lints.rust]
unused = "warn"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "hundred_parameter_benchmark"
harness = false

[profile.bench]
debug = true
